<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Mono.Cecil" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shop.Modular.Host\Shop.Modular.Host.csproj" />
  </ItemGroup>

</Project>
